### ISSUE TITLE
Possible optimization for COLR glyphs for sweep gradients with same start/end angle

### ISSUE THREAD

**Issue by LaurenzV** [googlefonts/fontations#1017]
From the COLR spec on sweep gradients:

```
If the color line's extend mode is reflect or repeat and start and end angle are equal, nothing shall be drawn.
```

From what I can see, this seems to apply for glyph 183 from the COLRv1 test glyphs font:

```
<BaseGlyphPaintRecord index="161">
  <BaseGlyph value="sweep_coincident_angles_forward_blue_red_reflect"/>
  <Paint Format="10"><!-- PaintGlyph -->
    <Paint Format="8"><!-- PaintSweepGradient -->
      <ColorLine>
        <Extend value="reflect"/>
        <!-- StopCount=4 -->
        <ColorStop index="0">
          <StopOffset value="0.0"/>
          <PaletteIndex value="4"/>
          <Alpha value="1.0"/>
        </ColorStop>
        <ColorStop index="1">
          <StopOffset value="0.3333"/>
          <PaletteIndex value="7"/>
          <Alpha value="1.0"/>
        </ColorStop>
        <ColorStop index="2">
          <StopOffset value="0.6667"/>
          <PaletteIndex value="8"/>
          <Alpha value="1.0"/>
        </ColorStop>
        <ColorStop index="3">
          <StopOffset value="1.0"/>
          <PaletteIndex value="0"/>
          <Alpha value="1.0"/>
        </ColorStop>
      </ColorLine>
      <centerX value="500"/>
      <centerY value="600"/>
      <startAngle value="90.0"/>
      <endAngle value="90.0"/>
    </Paint>
    <Glyph value="circle_r350"/>
  </Paint>
</BaseGlyphPaintRecord>
```

Nevertheless, when I draw that glyph using `skrifa`, I still get the command to draw that gradient. Would it be possible to implement this edge case in skrifa, so that if the sweep gradient has the same angles and repeat/reflect, the command isn't emitted in the first place? Or is there a reason why this isn't handled there (or am I missing something else)?

P.S.: For context, I'm trying to use `skrifa` to convert COLR glyphs into PDF objects, so I was trying to use the [Skia reference image from fontations](https://chromium-review.googlesource.com/c/chromium/src/+/5614312/16/third_party/blink/web_tests/platform/linux/virtual/text-antialias/colrv1-expected.png) for comparison. There, it seems like with spread mode pad it's drawn as expected, while with repeat/reflect it instead turns into a solid purple? 

<img width="167" alt="image" src="https://github.com/user-attachments/assets/f5952f11-f18e-491d-9df4-57fd77e34be6">

Do you know why this is the case, since, at least according to my understanding of the spec, nothing should be drawn at all?

**Comment by dfrg** [comment]
When we designed the color implementation, we tried to draw a line between transforms that are generally applicable to most renderers and those that are specific to Skia, particularly with regard to sweep gradients which have a lot of edge cases both in the spec and in Skia's shader implementation.

It's entirely possible that we were too conservative and there's more work that can be done here but I'm hesitant to make any changes without input from @drott who's currently on vacation. Let's keep this issue open so we can discuss when he returns.

**Comment by drott** [comment]
Yes, I think this a bug. Assuming that after angle conversion and color stop normalization, the angles are still equal somewhere here, we should not issue a paint command:
https://github.com/googlefonts/fontations/blob/main/skrifa/src/color/traversal.rs#L448
