### ISSUE TITLE
support vertical metrics tables vhea/vmtx

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontations#103]
As per discussions with Rod, we are leaning towards generating a single HVhea struct for both horizontal (hhea) and vertical (vhea) header tables, as well as a single HVmtx struct for vertical (vmtx) and horizontal (hmtx) glyph metrics tables, like harfbuzz is also doing, as the pairs of tables share the same or equivalent binary structure.

Which means we'll have to rename field names to work with both vertical and horizontal layout (e.g. advance_max instead of advance_width_max or advance_height_max. etc.), and also we shall gloss over differences like vhea.advanceHeightMax being typed as signed int16 in the TT/OT specs for legacy reasons while hhea.advanceWidthMax is (more correctly) an unsigned uint16; or the fact the vhea version is a fixed Version16Dot16 whereas hhea's version is a MajorMinor tuple (for version 1.0, they are both encoded the same as 0x10000).

**Comment by cmyr** [comment]
we can, if we wish, manually add separate getters with different names/return for fields that vary. We could even, if we desire, put these in a trait, and you would need to import the appropriate trait alongside the table? This would look like, say:

```rust
pub trait VmtxExt {
    fn v_metrics(&self) -> &[LongMetric];
    fn top_side_bearing(&self) -> &[i16];
}

impl<'a> VmtxExt for SharedHVmtx<'a> {
    fn v_metrics(&self) -> &[LongMetric] {
        self.long_metrics()
    }

    fn top_side_bearing(&self) -> &[i16] {
        self.side_bearing()
    }
}
```

although typing that out I think it would be easier to just use more generic names and avoid getting fancy. 🤷

**Comment by anthrotype** [comment]
> I think it would be easier to just use more generic names and avoid getting fancy. 🤷

exactly.. not sure it's worth the hassle

**Comment by anthrotype** [comment]
also, I think that trait of yours would let one, say, get `hmtx.v_metrics()` or `vmtx.h_metrics()` which makes things even more confusing

**Comment by anthrotype** [comment]
maybe two type aliases like `pub type Hmtx<'a> = HVmtx` and `pub type Vmtx<'a> = HVmtx` in each respective {read,write}_fonts::tables::{h,v}mtx modules, but I'm not sure what that would buy either.

**Comment by cmyr** [comment]
The trait would need to be imported for the methods to be available, at least; but yes if the trait was in scope then the methods would be available regardless of which concrete table you were dealing with.
