### ISSUE TITLE
Add TaggedTable trait and codegen attribute

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#109]
Today we don't know which types relate to which tag(s) in codegen. Add an attribute, e.g.

```rust
#[type_for_tag("cmap")]
table Cmap {
```

(name of attribute up for bikeshed)

**Comment by cmyr** [comment]
This should also have a corresponding trait in `read-fonts`. The trait would look like,

```rust
pub trait TaggedTable {
    const TAG: Tag;
}
```

Which is what we would implement if we saw this attribute on a table.

We can bikeshed this name. `TopLevelTable`? `RootTable`? `FontTable`? Nothing really jumps out at me.


In any case, this will let us further simplify the common case in `TableProvider`:

```
pub trait TableProvider<'a> {
    fn expect_table<T: FontRead<'a> + TaggedTable>(&self) -> Result<T, ReadError> {
        self.expect_data_for_tag(T::TAG).and_then(FontRead::read)
    }
    
    /// now our individual table getters generally just look like:
    fn head(&self) -> Result<tables::head::Head<'a>, ReadError> {
        self.expect_table()
    }
}
```

**Comment by cmyr** [comment]
> Also we should make sure this new attribute supports mapping multiple tags to the same table structure (see, hmtx/vmtx and hhea/vhea in #104)

This actually raises an interesting question: we can't have two impls of this trait for the same table, so as designed it doesn't work with `VHmtx` etc. I'm not sure what the best approach here is. A possible approach I can see is having a newtype wrapper for each concrete table that just implements this method + deref/derefmut? this doesn't feel wonderful either. I'll let this stew and see if another good solution presents itself.

**Comment by cmyr** [comment]
Added in #164
