### ISSUE TITLE
Crash serializing GDEF

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontations#1095]
In diffenator3, we use traversal to serialize the tables for diffing. When using `get_field` on a `gdef`, this code path is executed:

```
            3usize => Some(Field::new(
                "lig_caret_list_offset",
                FieldType::offset(self.lig_caret_list_offset(), self.lig_caret_list()),
            )),
            4usize => Some(Field::new(
                "mark_attach_class_def_offset",
                FieldType::offset(
                    self.mark_attach_class_def_offset(),
                    self.mark_attach_class_def(),
                ),
            )),
            5usize if version.compatible((1u16, 2u16)) => Some(Field::new(
                "mark_glyph_sets_def_offset",
                FieldType::offset(
                    self.mark_glyph_sets_def_offset().unwrap(),
                    self.mark_glyph_sets_def().unwrap(),
                ),
            )),
```

Everything looks good until we get to the `unwrap`s in branch 5. (I feel like library code should never `unwrap`, since it takes the app down with it.) If there is no `markGlyphSetsDefOffset`, the code will crash. Simple reproducer:

```
println!("{:?}", font.gdef());
```

**Comment by simoncozens** [comment]
I think there's some bad interaction between the nullable attribution and the version compatibility check.

**Comment by simoncozens** [comment]
This looks like a fix to the local problem, but breaks other stuff:

```diff
diff --git a/font-codegen/src/fields.rs b/font-codegen/src/fields.rs
index 24c76a7d..89d352dd 100644
--- a/font-codegen/src/fields.rs
+++ b/font-codegen/src/fields.rs
@@ -367,7 +367,14 @@ fn traversal_arm_for_field(
 ) -> TokenStream {
     let name_str = &fld.name.to_string();
     let name = &fld.name;
-    let maybe_unwrap = fld.attrs.conditional.is_some().then(|| quote!(.unwrap()));
+    let is_single_nullable_offset = fld.is_nullable() && !fld.is_array();
+    let maybe_unwrap = fld
+        .attrs
+        .conditional
+        .as_ref()
+        .filter(|_| !is_single_nullable_offset)
+        .is_some()
+        .then(|| quote!(.unwrap()));
     if let Some(traverse_with) = &fld.attrs.traverse_with {
         let traverse_fn = &traverse_with.attr;
         if traverse_fn == "skip" {
```

I could implement `Into<OffsetType>` for `Option<Nullable<T>>` but I don't know if that's the right thing to do.

**Comment by cmyr** [comment]
I believe this has been mentioned before, but traversal is slated to be removed or made private. I guess the only issue about this right now is https://github.com/googlefonts/fontations/issues/703?

In any case it is not being very aggressively tested or maintained, and there are definitely some buggy or unimplemented bits. The implementation does not (for instance) really work with conditional fields.

I'm personally of the opinion that it should be kept around, in which case I think it needs a solid rethink/rewrite, but it's hard to justify this at the moment.

**Comment by simoncozens** [comment]
> The implementation does not (for instance) really work with conditional fields.

PR above fixes that. :-)
