### ISSUE TITLE
Accessing a VarLenArray is really very slow

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontations#1106]
There's no bug here, but something for users to be very careful about. I realised that more than 90% of fontspector's runtime was spent getting a font's glyph names from the `post` table. No amount of caching helped. I boiled things down to the following test case:

```rust
use read_fonts::{
    tables::post::{PString, DEFAULT_GLYPH_NAMES},
    TableProvider,
};
use skrifa::FontRef;

fn main() {
    let font = FontRef::new(include_bytes!("../../RobotoSerif[GRAD,opsz,wdth,wght].ttf")).unwrap();
    for counter in 0..=1000 {
        std::hint::black_box(read_names(&font));
        read_names(&font);
    }
}

fn read_names<'a>(font: &'a FontRef<'a>) -> Vec<PString<'a>> {
    let post = font.post().unwrap();
    let strings = post.string_data().unwrap()
    let mut names = vec![];
    if let Some(index) = post.glyph_name_index() {
        for g in index {
            let idx = g.get() as usize;
            if idx > 258 {
                if let Some(Ok(entry)) = strings.get(idx - 258) {
                    names.push(entry)
                }
            }
        }
    }
    names
}
```

This took 90 seconds. When replaced with:

```rust
    let strings: Vec<Result<PString<'a>, _>> = post.string_data().unwrap().iter().collect();
```

it took 0.8 seconds.

So, if you're doing anything which deals with *more than one glyph name*, convert the `post.string_data()` VarLenArray into a Vec for a 100x speedup.

**Comment by cmyr** [comment]
yes, random access into a these types of collections is always in linear time, since we need to look at previous entries to know where the desired entry is found. To speed this up, the best approach would be to cache them somehow, as you mention; something as simple as,


```rust
let strings = post.string_data().unwrap().iter().collect::<Vec<_>>();
```

up front will show a massive speedup.

The docs for `get` mention that "This performs a linear search", but I agree that probably does not express the potential dangers in strong enough terms; I'll update the docs.

**Comment by simoncozens** [comment]
Updating the docs is fine, but few people use `VarLenArray` directly; the problem comes when other code uses it and ends up being silently slow. If e.g. calling `glyph_name()` is going to be slow, perhaps it would be worth adding a `glyph_names` metadata method to `skrifa::MetadataProvider` so that people who want more than one glyph name can get them all in one go without having to pay the price - I feel like that would be in scope for an "ergonomic, high-performance mid level library".
