### ISSUE TITLE
Autohinting activation and mode with `SmoothMode::kNormal` and `Engine::AutoFallback`

### ISSUE THREAD

**Issue by drott** [googlefonts/fontations#1151]
When integrating Fontations autohinting to Skia, in `SmoothMode::kSlight` and explicit Engine::Auto, things work well, and there are close to no differences to FreeType.  :+1: 

However, when configuring `SmoothMode::kNormal` and `Engine::AutoFallback` I see no difference to unhinted outlines in the output of Fontations. 

This also means, of course, that I see a difference in `SkFontHinting::kNormal` comparison between Fontations and FreeType, as it seems autohinting fallback does not get activated in Fontations.

Comparison: 

Left `SkFontHinting::kNone`, right `SkFontHinting::kNormal`, third column, comparison:

## SkTypeface backed by FreeType

Vertical stems get emphasized, the antialiased RGB color values are a touch "darker" left and right of the stems.

![image](https://github.com/user-attachments/assets/ba4da3a2-056c-48e7-86a9-72e2c763b815)

## SkTypeface backed by Fontations

No difference between `SkFontHinting::kNone` and `SkFontHinting::kNormal`, 
except, strangely, in combining mark placement, such as dots on Ü or circumflex.

![image](https://github.com/user-attachments/assets/fff0391b-b151-4aca-92c7-2e875dce1abe)

**Comment by drott** [comment]
Work in progress Skia integration CL:
https://skia-review.googlesource.com/c/skia/+/898577

**Comment by dfrg** [comment]
Testing on my end indicates that we appear to match FreeType's behavior here.

Specifically, if I load the 'a' glyph from the Noto Sans test font with FreeType and `FT_LOAD_TARGET_NORMAL`, FreeType does not select the autohinter. This is because the font contains a non-empty `cvt` table although it doesn't appear to have any real hinting instructions. This results in an outline that is identical to the one you get with `FT_LOAD_NO_HINTING`, matching the result we see for Fontations.

I'm not sure why Skia/FreeType is generating a hinted outline for `SkFontHinting::kNormal` in this case. I don't see anything in the Skia code that would trigger this behavior.

**Comment by drott** [comment]
For my Skia testing, this is with FreeType at [83af801b5](https://gitlab.freedesktop.org/freetype/freetype/-/commit/83af801b552111e37d9466a887e1783a0fb5f196). Are you using a similar revision?

Indeed, surprisingly, the font does have a prep table:
```
ttx -l -o- third_party/externals/googlefonts_testdata/data/fonts/NotoSans-Regular.ttf 
Listing table info for "third_party/externals/googlefonts_testdata/data/fonts/NotoSans-Regular.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    GDEF  0xECE6E9E7      2208    429572
    GPOS  0x9A4703EB     79042    431780
    GSUB  0xD9440714     49266    510824
    OS/2  0x0E5586E0        96       376
    cmap  0x10D913BC      3242     19280
    gasp  0x00000010         8    429564
    glyf  0x613D7F07    327789     41344
    head  0x23E954DF        54       252
    hhea  0x0CB317D6        36       308
    hmtx  0x519880AF     18808       472
    loca  0x2BE5BA5A     18812     22532
    maxp  0x1281017F        32       344
    name  0x1838217F      1900    369136
    post  0x08F04298     58527    371036
    prep  0x68068C85         7     22524
```

**Comment by drott** [comment]
Re:

> SkTypeface backed by FreeType

With Skia's `setSubpixel(false)` the differences between `SkFontHinting::kNone` and `SkFontHinting::kNormal` in the FT backend vanish:

![nosubpixel_ft](https://github.com/user-attachments/assets/38c2e4bc-4c13-499f-bc96-57a288472c97)

So, to summarize: The font has a prep table which disables the autohinter unless forced on. The horizontal stem differences are explainable through differing subpixel positioning in the two modes, which needs to be investigated separately.

Also @dfrg pointed out that the fontations backend does not perform subpixel path translation, as the freetype backend does before rendering, when subpixel rendering is requested. I will file that as a separate Skia issue.

**Comment by drott** [comment]
No issue here for Fontations.
