### ISSUE TITLE
klippa integration test fails if the Cmap4Iter bumps range start past end of prior range

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#1166]
As noted on https://github.com/googlefonts/fontations/pull/1101, if Cmap4Iter sets the start of the range to current.end + 1 this somehow results in klippa integration tests failing. E.g.

```rust
// Happy
self.cur_range = next_range.start.max(self.cur_range.end)
                    ..next_range.end.max(self.cur_range.end);

// Sad
self.cur_range = next_range.start.max(self.cur_range.end + 1)  // +1: no reason to reprocess the end of the prior range
                    ..next_range.end.max(self.cur_range.end);
```

Maybe I'm missing something obvious, at a glance this seems like a bug.

**Comment by dfrg** [comment]
The cmap4 code uses exclusive ranges so `next_range.start.max(self.cur_range.end + 1)` will skip an entry if the two ranges are contiguous.
