### ISSUE TITLE
[skrifa] NamedInstance.postscript_name_id "not present" case

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontations#1204]
In an [instance record](https://learn.microsoft.com/en-us/typography/opentype/spec/fvar#instancerecord), the postscript name ID is optional. `postscript_name_id` is therefore typed as `Option<NameId>`. All good.

However, in the binary, the "not present" case is represented as binary `0xFFFF`. When the postscript name ID is not present, both skrifa `NamedInstance.postscript_name_id` and read-fonts `InstanceRecord.post_script_name_id` do not return `None` but instead return `Some(65535)` - so in fact this `Option` always returns `Some`.

I feel that *certainly* in skrifa as a "mid-level" library, and possibly also in read-fonts, the "not-present" case should be interpreted from the binary value and returned as a `None`.

**Comment by dfrg** [comment]
Are you using an older version of read-fonts? This was changed a couple months ago: https://github.com/googlefonts/fontations/blob/d52fd0c7258701cdd52dd82be7937be9bc41684f/read-fonts/src/tables/instance_record.rs#L56

**Comment by simoncozens** [comment]
Sorry, yes, I was. Confirmed working OK now.
