### ISSUE TITLE
When avar2

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontations#149]
As we continue to make avar2 fonts, it would be great to see additional avar2 read and write features in more compilers :)

**Comment by dfrg** [comment]
Just talked with Behdad about that on Monday :) The additional work looks fairly simple (at least for reading) so I’ll knock it out soon.

**Comment by simoncozens** [comment]
Has there been any work on this? We are starting to need avar2-processed outlines through Skrifa.

**Comment by rsheeter** [comment]
Our top priority to deliver to Chrome is autohinting so @dfrg is focused on that.

Memory fails me, do we have sample avar2 fonts kicking around? - I imagine that would be handy once someone picks this up.

**Comment by dfrg** [comment]
See also: https://github.com/googlefonts/fontations/issues/1074#issuecomment-2276021329

Adding this functionality is mostly trivial but testing is a time sink which is why I haven’t prioritized it. As Rod mentions, pointing us to a font for that purpose might speed things along.

**Comment by simoncozens** [comment]
I'll take a look at doing it myself, no promises.

Some avar2 fonts:

* https://github.com/googlefonts/amstelvar-avar2
* https://github.com/googlefonts/roboto-flex-avar2
* Laurence's test font: https://github.com/Lorp/fencer/blob/main/fonts/avar2checkerVF-working.ttf - when AVAR is set to 100, glyph A will have its arrow pointing at the tick, and glyph B will have advance width of 1260.
