### ISSUE TITLE
Additional improvements to skrifa

### ISSUE THREAD

**Issue by dfrg** [googlefonts/fontations#209]
The initial punchcut PR (#191) has been lingering and we'd like to land it. This issue lists additional improvements that were requested during review but will be deferred to future PRs.

* Additional high level documentation-- help users understand what the library does and how to use it
* Typing adjustments:
    * ~~The `Variation` type should be better documented. This will be moved to `feta` as a generic type that supports both variations and feature settings.~~
    * ~~Newtype and rationale/description for unique font identifiers (currently raw u64). This also moves to feta as it will be necessary for shaping too.~~

**Comment by rsheeter** [comment]
Also coming up with a norse-themed name? :D

**Comment by dfrg** [comment]
Not sure how I missed that important requirement :)
