### ISSUE TITLE
Audit unsafe in read-fonts

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#228]
* Enumerate them all and get reviews

**Comment by cmyr** [comment]
Okay, so I've looked into this a little bit, and the current API does need some modifications.

For the record, the only tricky bit of unsafe in the codebase is the code for reading references and slices from raw bytes. The reference version looks like this (and the array version is fundamentally similar):

https://github.com/googlefonts/fontations/blob/087db1f531f87fdeb5e3c5ba003b8190432f31c9/read-fonts/src/font_data.rs#L105-L131

As mentioned in the comment at the top of that first wrapper function, there *is* a problem with the current API, and the use of the `FixedSize` trait, here.

Put simply, `FixedSize` does not fully capture the constraints we want.

To refresh everyone's memory:
- we have a concept of `Scalar` types, which are types that can be read from a fixed length of raw bytes.
- There is a helper, `BigEndian<T>`, where `T: Scalar`. `BigEndian<T>` is basically a typed byte slice of fixed length, where the length is the number of bytes required to represent `T`. 

For these APIs: we want to only support unsafe casts for `BigEndian<_>` types, as well as for packed, unaligned structs where all members are `BigEndian<_>` types. We should have some additional marker trait, (`CastSafe` or something) that we implement only for `BigEndian<T>` and for structs containing only `BigEndian` members, and this trait should used to constrain these unsafe methods.
