### ISSUE TITLE
Reconsider release strategy

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontations#256]
The main change I am uncomfortable with is having a single version for all crates in the repo. I think this is a misuse of the `workspace.package` concept, and I think it can have concrete negative consequences.

The `workspace.package` setting is (as far as I understand it, which is imperfectly) intended in the case where you have a large project that is split across multiple crates, but where there is a single 'main' package that is published. This isn't really what we're doing. In our case, we are maintaining related but independent crates in a single repository, but we fully expect (for instance) that some projects will depend on `read-fonts` without caring about `write-fonts`.

The problem with having a single version for everything is that it strips out the *semantic* bit of semver. This could actually impact downstream crates.

A concrete example:
- All of our crates are at `v0.1.0`.
- Imagine a crate, `font-adjuster`, that depends on `read-fonts`.
- Imagine a crate, `font-compiler`, that depends on `font-adjuster` and `write-fonts`.
- We make a breaking change to `write-fonts`. We do a new release, and all our crates are at `v0.2.0`.
- `font-compiler` updates its `write-fonts` dep to the new version.
- `font-compiler` no longer compiles, because `font-adjuster` has not been updated.

This is annoying and unnecessary. `read-fonts` is unchanged, but we now have two incompatible versions of an identical library. Any users of our crates will have to make sure any deps that might also rely on these crates are always on the latest version of all of those crates, even if there are no actual changes to the crates they are using.

I don't think we want this. As far as I can tell, the motivation was largely to make it easier for us to do releases, but I think between tools like [`cargo-release`](https://github.com/crate-ci/cargo-release) and [`cargo-set-version`](https://github.com/killercup/cargo-edit#cargo-set-version) we have ways of simplifying our release process without breaking the compatibility benefits of semver.

I'm going to investigate these tools a bit more, and then I will propose a release process that tries to keep things simple while still maintaining semver.

**Comment by rsheeter** [comment]
Agreed, we should undo the single version change. I think things got confused by the arguably incorrect handling of semver by cargo (the leftmost not 0 thing in https://doc.rust-lang.org/cargo/reference/semver.html#change-categories). The real solution appears to be to start at 0.1.0.

**Comment by rsheeter** [comment]
Concretely I suppose we just need to nuke the script that does global updates or make it do more targeted updates?

**Comment by cmyr** [comment]
There's a bunch of tools out there for managing versioning and releases, but they're all either too smart or too dumb. 😒

I'm going to dig a bit more, but I think my current course of action:

- revert single version change
- get rid of the script
- write up release instructions, but make use of existing tools like `cargo-set-version` to automate a bunch of it.

**Comment by rsheeter** [comment]
https://crates.io/crates/set-cargo-version appears to be pretty unused? - I might prefer a script we own over that.

**Comment by rsheeter** [comment]
Closing as I believe this is now in good shape.
