### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontations#303]
I'm trying to use `fea-rs` but `write-fonts` is dying:

```
$ RUST_BACKTRACE=1 cargo run ./features.fea --glyph-order glyphorder -o Gulzar-Regular.ttf
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/fea-rs ./features.fea --glyph-order glyphorder -o Gulzar-Regular.ttf`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/write-fonts-0.1.5/src/write.rs:72:59
```

Relevant bit of backtrace seems to be

```
   4: write_fonts::write::dump_impl
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/write-fonts-0.1.5/src/write.rs:72:13
   5: write_fonts::write::dump_table
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/write-fonts-0.1.5/src/write.rs:47:8
   6: core::ops::function::FnOnce::call_once
             at /rustc/470e518c4b43265020c882bcf3c86632f5494910/library/core/src/ops/function.rs:251:5
   7: core::option::Option<T>::map
             at /rustc/470e518c4b43265020c882bcf3c86632f5494910/library/core/src/option.rs:922:29
   8: fea_rs::compile::lookups::contextual::compute_size
             at ./fea-rs/src/compile/lookups/contextual.rs:648:5
```

**Comment by rsheeter** [comment]
Can you add more specific steps to reproduce? -  e.g. where to obtain the input files, etc. IIRC Gulzar has notably complex features so bonus points for a simplified repro case.

**Comment by simoncozens** [comment]
Here's a minimal reproducer:

[features.fea.gz](https://github.com/googlefonts/fontations/files/11059441/features.fea.gz)
[glyphorder.txt](https://github.com/googlefonts/fontations/files/11059442/glyphorder.txt)
[Gulzar-Regular.ttf.gz](https://github.com/googlefonts/fontations/files/11059444/Gulzar-Regular.ttf.gz)

Looks like it's having problems with overflowing GSUB6 lookups.

**Comment by cmyr** [comment]
Just seeing this now, will investigate! sorry for the delay :)

**Comment by cmyr** [comment]
Okay yea investigating this I see that our table packing algorithm does not currently implement either subtable promotion (using extension subtables in GPOS/GSUB) or table splitting. This was good enough to get us started, but the work is incomplete.

I suspect that adding extension promotion should solve most of our problems, and we can look into table splitting after that.

**Comment by simoncozens** [comment]
I'm sure that improved table packing would help. At the same time, there are a surprising number of `.unwrap()`s in a row in that part of the code.

**Comment by cmyr** [comment]
and a glaring TODO about returning a meaningful error. I'll at least do something to improve the diagnostics..
