### ISSUE TITLE
FontBuilder should set searchRange, entrySelector, and rangeShift

### ISSUE THREAD

**Issue by madig** [googlefonts/fontations#314]
Code like `let cmap_table = tables::cmap::Cmap::from_mappings([]);` seems to produce a `subtable_offset: +12` when fontTools produces `subtable_offset: +20` (according to otexplorer). Ots then complains as thus:

```
WARNING: bad table directory searchRange
WARNING: bad table directory entrySelector
WARNING: bad table directory rangeShift
File sanitized successfully!
```

**Comment by rsheeter** [comment]
The warning appears to be complaining about https://learn.microsoft.com/en-us/typography/opentype/spec/otff#table-directory. I bet nobody ever set those to anything.

How would one reproduce the complete font you are feeding to OTS, is your code making a font and sticking a blank Cmap into it?

**Comment by madig** [comment]
Ah, maybe it's that instead. You can do `cargo run` in https://github.com/madig/toy-font-compiler/blob/main/Cargo.toml and inspect /tmp/f.ttf :)

**Comment by rsheeter** [comment]
Nit: it would be nice to use git deps or versioned deps not path; my path didn't match so I had to hack Cargo.toml to make it go.

xxd seems to confirm this is due to the table directory so I think there is no bug with Cmap:

```shell
xxd -l 12 -c 2 /tmp/f.ttf
00000000: 0001  ..  # sfntVersion
00000002: 0000  ..  # sfntVersion
00000004: 000a  ..  # numTables
00000006: 0000  ..  # searchRange
00000008: 0000  ..  # entrySelector
0000000a: 0000  ..  # rangeShift
```

**Comment by rsheeter** [comment]
Updating subject as I do think a change is warranted.
