### ISSUE TITLE
check_no_println not found when run via githook?

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontations#320]
so I have set git to use `resources/githooks` as my `hooksPath` (`git config core.hooksPath "./resources/githooks"`) and now `git push` is failing with the following:

`resources/githooks/pre-push: line 42: ./../scripts/check_no_println.sh: No such file or directory`

I assume that git is running the hooks via an alias or something, and so this isn't working? Does anyone else have this working as an actual git hook?

**Comment by anthrotype** [comment]
strange.. it does work for me on both macOS and Linux. I also have done `git config core.hooksPath "./resources/githooks"` like you did.
The pre-push script gets its own directory (resources/githooks) like this, and then finds the sibling "scripts" directory where the check_no_println.sh script is located:

https://github.com/googlefonts/fontations/blob/a7f913047a99ea9fbd8460a8a4797876c3fb81d5/resources/githooks/pre-push#L7-L8

and calls it like that:

https://github.com/googlefonts/fontations/blob/a7f913047a99ea9fbd8460a8a4797876c3fb81d5/resources/githooks/pre-push#L42

**Comment by anthrotype** [comment]
@cmyr if this is more of a hindrance, feel free to remove that

**Comment by cmyr** [comment]
hmmmm okay this is curious, I'll play around a bit more. I get this error on every push, currently.

**Comment by cmyr** [comment]
Okay, so the issue is that `realpath` is not present on macOS by default; you need to install `coreutils`.

**Comment by anthrotype** [comment]
We don't have to use realpath, we don't actually care about symlinks for our limited use case, we can get away with something else to obtain the absolute path, e.g. see most voted solution in this SO link https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
