### ISSUE TITLE
Get a list of supported codepoints

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/fontations#390]
Both `skrifa` and `read-fonts` offer to map a codepoint to a glyph for me, but I just want a list of what codepoints are supported by a font. Ideally, I'd just love a hashmap or similar mapping codepoints to glyph IDs.

Currently I'm having to do this, which does not feel ergonomic:

```rust
pub fn codepoints(&self) -> HashSet<u16> {
        let cmap = self.fontref().cmap().expect("Couldn't parse cmap table");
        let mut points = HashSet::new();
        let records = cmap.encoding_records();
        for record in records {
            if let Ok(subtable) = record.subtable(cmap.offset_data()) {
                match subtable {
                    CmapSubtable::Format4(c) => {
                        for (start, end) in c.start_code().iter().zip(c.end_code().iter()) {
                            for point in start.get()..end.get() {
                                points.insert(point);
                            }
                        }
                    }
                    CmapSubtable::Format12(_) => todo!(),
                    _ => {}
                }
            }
        }
        points
    }
```

**Comment by dfrg** [comment]
Would a method like this
```rust
fn for_each(&self, f: impl FnMut(u32, GlyphId));
```
on the subtables (and skrifa `Charmap`) be sufficient?

@drott I think this might be useful for you as well

**Comment by rsheeter** [comment]
I'm curious why `for_each(fn)` instead of something like `iter() -> Iterator<Item=(Codepoint, Gid)>`

**Comment by simoncozens** [comment]
Same trick goes for nameIDs, by the way. You can map a nameID to a string if I ask you for a certain nameID, but you can't help me if I ask for what nameIDs are present.

**Comment by dfrg** [comment]
> I'm curious why `for_each(fn)` instead of something like `iter() -> Iterator<Item=(Codepoint, Gid)>`

Doable but the code is more complex and it'll get really nasty if we want to offer a generic version on the skrifa side that abstracts over the subtable that was selected. This is one of those cases where `impl Iterator` doesn't compose well.

This would basically break down to a named public iterator for each subtable and an iterator on the skrifa side that holds an enum of subtable iterators... so I proposed the callback version instead :)

> Same trick goes for nameIDs, by the way.

This one should be simple enough with read-fonts:
```rust
let name_ids: HashSet<NameId> = font
    .name()
    .unwrap()
    .name_record()
    .iter()
    .map(|rec| rec.name_id())
    .collect();
```

**Comment by simoncozens** [comment]
>  the code is more complex and it'll get really nasty 

I tend to think that the purpose of a library is to be convenient for the library user, not the library author... :-)

**Comment by dfrg** [comment]
Ask an ye shall receive :)

#399 also includes an iterator for the UVS subtable for good measure.
