### ISSUE TITLE
write-fonts: put logging behind a feature

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontations#397]
I think the best way to do this is going to be to have our own set of macros that use `#[cfg(...)]` to either generate the actual log calls or to no-op, based on the presence of the feature.

**Comment by rsheeter** [comment]
dot2 as well, per https://github.com/googlefonts/fontations/pull/396#discussion_r1190075867

**Comment by cmyr** [comment]
Okay so I have some more info on this:

the `log` crate itself provides a [set of features](https://docs.rs/log/latest/log/#compile-time-filters) that let a crate choose, at compile time, what level (if any) of log messages it wants to be compiled into the binary.

Due to the nature of rust features, enabling one of these in one place in the graph means it is enabled everywhere, so the `log` crate itself says it should not be used by library crates.

This does mean, though, that any tool *using* `write-fonts` has a simple way of ensuring no logging ends up in the final binary, which solves the underlying issue this is tracking.
