### ISSUE TITLE
Use a u64 for ObjectId

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontations#398]
Because maybe once day this does get used in a long-running process or something?

              > QQ: `ObjectId`s are allocated with a global `usize` counter. Should we change this to an explicit `u64` (or allocate ids locally in the graph) to avoid potential overflows if someone does decide to run this on a 32-bit system?

Hmm... I would expect the process to only be running for a specific compilation, which even in the case of a very large multi-access font it's hard to imagine there being 4.2e9 unique objects? And in that case I would definitely expect us to be on a 64-bit system. That said, it wouldn't *hurt*...

_Originally posted by @cmyr in https://github.com/googlefonts/fontations/issues/388#issuecomment-1542515221_

**Comment by rsheeter** [comment]
Use of a global long-lived counter sounds like the problem more than the type?

> I would expect the process to only be running for a specific compilation

We should assume we could exist in a long-lived high traffic process.

**Comment by rsheeter** [comment]
> We should assume we could exist in a long-lived high traffic process

On that note, is there anything else that assumed short-lived single-compilation use?

**Comment by rsheeter** [comment]
Naively, an id generator whose scope is other than global, is something stopping us? Client could pass in an IdGenerator where needed?

**Comment by cmyr** [comment]
Certainly possible; and it would also be possible to have a unique counter for each graph under compilation, but it ends up being more work and more complexity (since you then need to hold on to this counter and make sure it is accessible anywhere that you might need to create an id)
