### ISSUE TITLE
release.sh script ignores arguments?

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontations#437]
When you call `release.sh` it wants you to pass a crate name, but then it calls `cargo publish` without passing along this argument? Currently the script cannot publish `write-fonts` because it is failing when it tries to publish an already-existing version of `font-types`.

**Comment by rsheeter** [comment]
Someone should fix that!

**Comment by rsheeter** [comment]
https://github.com/googlefonts/fontations/blob/main/resources/scripts/bump-version.sh#L29-L33 shows bump-version.sh obeying. For some reason in release.sh it looks like I established a crates variable and then went on to completely ignore it.

**Comment by cmyr** [comment]
I played around with this a bit and I'm not sure there's a better solution. When I respect the names and use the loop, then it will fail during dry-run if any of the crates we're trying to publish have dependencies on other crates we're trying to publish (since it can't find them in the registry, as they aren't published yet) and then publishing will likely fail since it won't know to wait between publishing crates so that it has time for the registry to update.

It also does seem to work for publishing a single crate as long as other crates don't have changes; in the less-common case where we want to be more selective it isn't too hard to just do it by hand.

**Comment by rsheeter** [comment]
Sorry, one more question, would it not still be marginally better if it respected names? It will correctly fail if a dependency doesn't exist but I think it would mean that things that don't have dependencies could be pushed independently? For example, I could bump skrifa and write-fonts and then release one but not the other even those both are pending?

**Comment by cmyr** [comment]
I agree that would be nice, but i'm not sure the best way to do it?

Actually thinking out loud, maybe there is a reasonable way: instead of having the user provide a list of all the crates they want to publish, they should either pass *no arguments* (which means publish everything) or they can pass a *single crate*, in which case we would only target that crate. 

This would save us from needing to use a loop (which didn't work in my earlier experiments) and if you wanted to publish exactly two crates then you could just run the script twice.

I'll play around with this and see if it works next time I need to do a release, which should be soon.

**Comment by rsheeter** [comment]
I just ran into this with write-fonts : I ran the script, it asked me if I wanted to publish all the things:

```shell
Publish
  font-types 0.2.0
  read-fonts 0.4.0
  write-fonts 0.6.2
  skrifa 0.3.0
? [y/N] 
```

I actually wanted to publish only write-fonts but the script doesn't make that easy for me, I had to run the commands by hand with `-p write-fonts`. I would think we want the same loop as bump version.

**Comment by cmyr** [comment]
as mentioned above, the loop doesn't work, but we could change the semantics to be either "publish everything" or "publish a single crate".

**Comment by rsheeter** [comment]
Why doesn't the loop work exactly? - I just ran through the commands from the shell script passing `-p write-fonts` each time and it seemed just fine.

**Comment by cmyr** [comment]
See this comment: (https://github.com/googlefonts/fontations/issues/437#issuecomment-1572506151)

basically:
- it fails in dry run if any crate depends on another crate (of ours) since it won't be published yet
- publishing can fail for crates with dependencies if the new dependency version hasn't propagated on crates.io yet.
- also it matters what order you publish crates in, so you would have to specify them in the correct order on the command line (unless we use something to resolve the dependency graph and produce a topographic order, which I do not seriously propose), which could be *just barely* tolerable but feels pretty bad.

**Comment by rsheeter** [comment]
I believe that still leaves cases where it will work, for example write-fonts and skrifa, and it will fail if you try to use it in a way that won't work. It will fail safely - not do something bad - if you use it poorly so it's relatively harmless. You have to have some care in ordering and how you update version #s but ... that's true regardless.

To be fair, everything or just one would suffice and would be far more useful than what we have now.
