### ISSUE TITLE
PartialEq for all write types?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#532]
It would be helpful for the compiler to be able to check if an instance of a write type changed using == but the types don't consistently implement partialeq. Maybe write-types should just always have Capability::Equality?

Context https://github.com/googlefonts/fontc/pull/359#discussion_r1252423322

**Comment by cmyr** [comment]
Yea, I think this makes sense. Do we also want to add Ord/Hash?

**Comment by cmyr** [comment]
if we add them all then I can delete some codegen code, and there isn't a ton of downside; maybe slightly slower compilation, but the compiled code should get stripped if it's unused

**Comment by cmyr** [comment]
I'm going to go ahead and try that, I think it'll save us future headaches.

**Comment by rsheeter** [comment]
I don't find it as obvious that Ord and Hash make sense for everything?

**Comment by cmyr** [comment]
They're necessary if we ever want to put any of these types in a set. Overall none of these traits are 'always necessary', but we don't have perfect foresight of when they will be necessary, and the alternative (some ability to add them as needed in codegen) is more complicated and more work overall.
