### ISSUE TITLE
Consider adding `Glyph::Empty` variant?

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontations#561]
This would be used in both read&write-fonts, and would correspond to the situation where we do not write any glyph data, but add a (zero-length) entry in the loca table.

Does this make sense? It feels like it would improve the API, at the cost of a minor deviation from the spec. It might also let us add more invariants in `write-fonts` enforcing that non-empty glyphs have at least one contour/component.

              General curiosity: should we have an `Empty` variant? This is a bit weird on the read-fonts side too. I believe I updated the loca table at some point to return `Result<Option<..` to capture this but it didn't feel good.

_Originally posted by @dfrg in https://github.com/googlefonts/fontations/pull/558#discussion_r1283458667_

**Comment by anthrotype** [comment]
Yes, I like this idea.
In fonttools, for empty glyphs we return a glyf.Glyph() object which has numberOfContours == 0, thus is neither a composite glyph (numberOfContours = -1) nor a simple glyph (numberOfContours > 0)

**Comment by rsheeter** [comment]
+1 to explicit Empty
