### ISSUE TITLE
[skrifa] Small advance differences in Noto Sans between FT and Fontations

### ISSUE THREAD

**Issue by drott** [googlefonts/fontations#590]
I haven't reduced this to FT calls vs. Fontations calls yet, but in my comparison of Skia backends I get:

```
fontations: 
gid: 36 advance: 15.33600044250488281250 gid: 68 advance: 13.46399974822998046875 gid: 47 advance: 12.57600021362304687500 gid: 79 advance: 6.19199991226196289062 
ft: 
gid: 36 advance: 15.33595275878906250000 gid: 68 advance: 13.46395874023437500000 gid: 47 advance: 12.57595825195312500000 gid: 79 advance: 6.19198608398437500000 
```

For Noto Sans which triggers in the tests that I am developing for path and metrics equality.

Both `SkFont` objects are configured in Skia as follows:

```
                font.setSize(24);
                font.setEdging(SkFont::Edging::kSubpixelAntiAlias);
                font.setSubpixel(true);
                font.setHinting(SkFontHinting::kNone);
```

**Comment by drott** [comment]
@dfrg have you observed similar differences - is this expected due to the different internal representation of `FT_GlyphSlotRec`'s `advance` (`FT_Vector` of `FT_Pos`, 26.6) or 16.16 of `linearHoriAdvance`?

For the first case: 15.336... - 15.335953 - the difference is:
0.000047684 i.e. less than 5/100000th of a Pixel, if I counted that right.

From the fixed point and floating point math differences between FT and Fontations, Can we define a theoretical tight error limit of how much the FT and the fontations result may differ?

**Comment by dfrg** [comment]
I haven’t checked specifically against the advance in the glyph slot. My tests so far used `FT_Get_Advance` which may have slightly different results. Also, with a delta that small, I’m wondering if this may be a difference of `/ 64.0` vs `* 1.0/64.0` for the 26.6 to float conversion. I’ll dig deeper into this.

**Comment by dfrg** [comment]
Following up, the difference here is based on how scaling factors are applied:

* FreeType: `FT_MulDiv(metric, scale, 64)` where `metric` is in font units, `scale` is a font unit -> 26.6 conversion and the final division by 64 converts to 16.16.
* HarfBuzz: returns metrics in font units unless you specify your own (fixed point) scale factor. For example, `hb_font_set_scale(font, 24 * 64, ...)` would set a scale for 24 ppem with 6 bits of precision. I believe the result is computed with (integer arithmetic): `metric * scale / upem`.
* Skrifa: creates a single floating point scale factor with `ppem as f32/upem as f32` and applies that directly to all metrics.

Of course, skrifa can return font units as well by passing `Size::unscaled()` when constructing the metrics types, in which case we can match any of these methods. I suppose the question is what we should return by default when applying a scale. Any preference?

**Comment by rsheeter** [comment]
Given our goals here my naive thought is the default should be "what FreeType does"; is that a bad idea?

**Comment by dfrg** [comment]
I think “what FreeType does” is perfectly reasonable. It’s not 100% straightforward though. The `advance` and `linearHoriAdvance` fields on the glyph slot are typically different (they’re scaled differently) so we’d have to choose one.

**Comment by drott** [comment]
@behdad do you have any opinions or past experience with regards to working with floats vs. fixed point for the returned advance values?   

Thanks for the analysis above. How are `advance` and `linearHoriAdvance` scaled differently exactly? 

What we do need in the SkTypeface backend implementation is a mode where we get an advance that works for "linear metrics mode", i.e. where the advance is not affected by rounding or hinting and where the resulting metrics would work for upscaling and downscaling a text run without reshaping. But I think that can be done already with Skrifa by configuring the scaler settings accordingly.

I think for testing, instead of working with scaled values for the advances, I can avoid an error or difference by working with `Size::unscaled()` and also either not scaling or scaling to `upem = ppem` in FreeType, and perhaps this way I can get to equal  results?

I don't think we need to introduce an artificial precision reduction before converting to float - if that's what "making it do the same thing as FreeType" would mean in this case.

**Comment by behdad** [comment]
> @behdad do you have any opinions or past experience with regards to working with floats vs. fixed point for the returned advance values?

I don't. I agree testing at upem scale would be best. We've seen some rounding differences before for weird values of upem.

**Comment by drott** [comment]
Even at upem scaled size (setting that as font size for the scaler, might not be the exact same behavior as `Size::unscaled() ` or is it?) I can't compare the advances as equal. There's tiny differences.

> Thanks for the analysis above. How are `advance` and `linearHoriAdvance` scaled differently exactly?

I looked [at these FreeType docs](https://freetype.org/freetype2/docs/tutorial/step2.html#:~:text=The%20metrics%20found%20in%20face%2D%3Eglyph%2D%3Emetrics) which explains that to some extent. `advance` is 26.6 and usually rounded to 1/64th so an integer pixel value, linearHoriAdvance seems to have higher resolution in 16.16 format. - but I wonder if the latter always ignores hinting.

I don't think the part of "usually rounding to pixels" is up to date information in the documentation, I don't see that happening.

We do need something for Skia to perform something similar to the previous "SkFont::setLinearMetrics" behavior - but we can probably do that with a separate Skrifa scaler configuration that disables hinting. We just need to figure out better what exactly the specific things mean which FreeType returns.

**Comment by drott** [comment]
> Of course, skrifa can return font units as well by passing Size::unscaled() when constructing the metrics types, in which case we can match any of these methods. 

If the font units advance value would be an integer value, is that always true after hinting or autohinting as well? Or could it theoretically become fractional after these processes? (I guess not?) 

I am trying to make up my mind what would be the benefits of differences in precision across the font size spectrum with floats vs. predictability in testing and computation with a fixed point value here. I am not decided on that. On the Skia side the interfaces are all `SkScalar = float`, so we anyway convert to those after we receive them from the font libraries. In Blink we work with floats and convert to `hb_position_t` where needed.

**Comment by dfrg** [comment]
I do believe linearHoriAdvance never takes hinting into account.

The advance field is 26.6 and is computed by subtracting the first phantom point from the second after variations and hinting are applied.

If we compare at upem scale, we should get integral values. For variable advances, FreeType truncates fractional bits on deltas (which we also do in skrifa).

**Comment by dfrg** [comment]
Oh, and yes, hinting can generate fractional advance values though I think this is fairly rare in practice now. Modern FreeType enables the light hinting mode by default which prevents movement in the horizontal direction based on the backward compatibility flag.

**Comment by drott** [comment]
> If we compare at upem scale, we should get integral values. For variable advances, FreeType truncates fractional bits on deltas (which we also do in skrifa).

When working with NotoSans-Regular and retrieving the advance value at upem scale 1024 (not with Size::unscaled()), I do get ([with the Skia / Fontations ffi code](https://source.chromium.org/chromium/chromium/src/+/main:third_party/skia/src/ports/fontations/src/ffi.rs;l=102?q=ffi.rs%20skia)) a couple of values that are not integer, examples:
```
gid: 36 advance: 639.0000610352 gid: 36 advance: 639.0000610352 gid: 49 advance: 760.0000610352 gid: 42 advance: 728.0000610352 gid: 40 advance: 556.0000610352 gid: 54 advance: 549.0000000000 gid: 44 advance: 339.0000305176 gid: 40 advance: 556.0000610352 gid: 49 advance: 760.0000610352 gid: 3 advance: 260.0000305176 gid: 80 advance: 935.0000610352 gid: 76 advance: 258.0000305176 gid: 81 advance: 618.0000000000 gid: 68 advance: 561.0000610352
```

I need to investigate that more, this might be a bug in the ffi or Skia implementation. But it would be useful to add a test for that on the Fontations side. The integer numbers in that float exponent range should be exactly representable. 

Related, but a bit nitpicky: I am not sure Size::unscaled() should be represented as 0 - if I read that right the code would not be handling `Size::new(0)` differently from that, would it? And size(0) means something else.

**Comment by drott** [comment]
As [discussed in TPAC f2f](https://docs.google.com/document/d/1A7d3c1xXpVUQASAEfcwhZ2vxY2g_qRumc5fRszLqBUw/edit?resourcekey=0-MmP7c7y2eMOSPQPHVoNHzQ#bookmark=id.vasfu1dn0d4), let's aim to bring results as close as possible to FreeType, even if that may require simulating fixed point calculations before converting to float.

Any updates on this, in particular the differences at unscaled size above, @dfrg?

**Comment by dfrg** [comment]
Not yet. I’m still in Europe until Tuesday but I’ll prioritize this as soon as I’m back
