### ISSUE TITLE
Just a 'Thank You'

### ISSUE THREAD

**Issue by moontypespace** [googlefonts/fontations#622]
I just wanted to thank you for the documentation I found here:
https://github.com/googlefonts/fontations/blob/f8a8ccfd716200f36c02b9477b1e6f3768bf9d04/write-fonts/src/lib.rs#L91

That's very helpful :)

**Comment by rsheeter** [comment]
I'm glad you found it helpful, please let us know if you try it and encounter problems :)

**Comment by moontypespace** [comment]
> I'm glad you found it helpful, please let us know if you try it and encounter problems :)

I just tested a few code snippets (modified a OS/2 value instead of the head table), but they worked fine:
<img width="1805" alt="Screenshot 2023-09-24 at 11 39 16" src="https://github.com/googlefonts/fontations/assets/21055547/5f4c8a3d-479c-452c-b13b-d9febcdab5f4">
