### ISSUE TITLE
Consider exposing `Colr::ResolvedPaint` paint parameter value types to `f32`

### ISSUE THREAD

**Issue by drott** [googlefonts/fontations#673]
Similar to how we expose metrics as f32 but ensure their resulting value is computed the same way as in FreeType, I think we should expose the resulting COLRv1 parameters in `ResolvedPaint` as `f32` for consistency with metrics. 

Thoughts? Was there a particular reason for exposing them as `Fixed` so far?

**Comment by dfrg** [comment]
While we don’t have an explicit policy, so far we’ve generally avoided floating point in `read-fonts` and have tried to keep the model as close to the specification as possible. This also facilitates direct comparisons to FT as `ResolvedPaint` is a fairly close match to `FT_COLR_Paint`. 

That said, this particular code does substantial processing so could be an exception. If you’re not making use of this directly in the Skia ffi code, we could arguably just move it to skrifa as a private module and modify it as needed.

**Comment by drott** [comment]
Good point about the boundary between skrifa and read_fonts with regards to what data types to use. I think I can do the conversions on the Skrifa side then when implementing the COLRv0/v1 driver.
