### ISSUE TITLE
Publish LICENSE files for read-fonts and font-types

### ISSUE THREAD

**Issue by drott** [googlefonts/fontations#711]
Compare https://bugs.chromium.org/p/chromium/issues/detail?id=1503143
Currently inquiring from @danakj on the issue where these files should become visible for our checker tool to pick them up.

**Comment by drott** [comment]
From @danakj 's comment in https://bugs.chromium.org/p/chromium/issues/detail?id=1503143#c2 it sounds like the request is to publish the LICENSE files into the crate, if that's not done yet? Is there something we can do so that those get downloaded with downloading the crate?

**Comment by cmyr** [comment]
okay so it looks like we're missing the [`license-file` manifest key](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields). Interestingly, while you can specify multiple licences in the `license` field, you can't do this for the `license-file`. So:

- should we combine our two licenses into one file,
- or should have `license-file` point to one of the two licenses,
- in which case, which one?

I'll look and see if there's prior art for the first option...

**Comment by cmyr** [comment]
Okay I have a better/more expedient solution: let's just copy the license files into the root of each crate, and then cargo will just bundle them up like anything else. This is slightly inelegant but will solve our actual problem, which is satisfying which is satisfying gnrt.

**Comment by drott** [comment]
Thanks for looking into this! Does Cargo bundle them if they are not copied but symlinked?

**Comment by cmyr** [comment]
I was wondering the same, I can investigate...

**Comment by drott** [comment]
Thanks for the quick fix. If you'd publish a version for font-types and read-fonts, I think Dana could roll that into Chromium and we could close the upstream issue in isolation. @danakj is in the middle of improving dependency management in Chromium for Rust packages - so it'd be nice to get that sorted and cleaned up.
