### ISSUE TITLE
Drop `#[nullable]`?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#76]
Every offset could be null and the compiler forces the consumer to be ready for it (yay!). Encoding `#[nullable]` is basically capturing a validation, that it _shouldn't_ be null. We don't capture validation rules for other fields, perhaps we shouldn't capture this one?

**Comment by rsheeter** [comment]
Relates to desire in #68 to have less attributes.

**Comment by cmyr** [comment]
What `nullable` is trying to represent is the distinction between offsets that are *explicitly* allowed to be null, versus offsets that are not. This is a useful distinction, I think? Particularly when compiling fonts, if a non-nullable offset is null, we will error, but if a nullable offset is null we don't, and so we will want to have access to this information *somehow*...

**Comment by rsheeter** [comment]
A client of the parser will make their own choices about what to do with a missing field and will do so for every offset whether it's "allowed" to be null or not.

A client of the writer will have to validate many things. Most of them we don't include in the schema. For example, it's not great to emit a transform with a null matrix but we don't encode that in the schema.

I find it a bit weird that this one validation is captured but no others. Feels like there's a principle that we're right on the edge of violating.

**Comment by cmyr** [comment]
Another analogy would be to `GlyphId`; the spec does not treat `GlyphId` as a distinct type, but we have decided it is ultimately beneficial to do so.

I do agree that `nullable` is less important in the case of reading than it is in the case of writing, where we *do* want to ensure that offsets are not null where that is not expected; if we wanted to remove this annotation I suspect we would want to manually add validation code on a per-field basis.

Is your main complaint the generation of `Option<Result<_>>`?

**Comment by rsheeter** [comment]
> Is your main complaint the generation of Option<Result<_>>?

I think it's strange that we encode a very specific subset of validation into the schema. It feels ... inconsistent.

**Comment by rsheeter** [comment]
I don't feel strongly enough about this to push hard for it. Feels weird, but not so weird it *has* to be fixed.
