### ISSUE TITLE
When codegen fails a backtrace is nice

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#82]
I found it very helpful to have `eprintln!("{}", Backtrace::capture());` before places that return syn::Error's when modifying the codegen. Without it the lovely error told me where in the input the problem was but not so much where in the codegen it might be.

I wonder if it's worth having that as a standard practice?

**Comment by rsheeter** [comment]
Maybe in a debug log?

**Comment by rsheeter** [comment]
https://doc.rust-lang.org/std/backtrace/index.html is experimental; blocked on https://github.com/rust-lang/rust/issues/53487

**Comment by rsheeter** [comment]
Backtrace is no longer experimental in 1.65

**Comment by cmyr** [comment]
Also I realized something about this tension (between showing backtraces versus showing the inline errors) and perhaps i commented on this somewhere earlier? But basically the backtraces are useful if you're working on the actual codegen tool itself, but the inline errors are much more useful if you're working on some other table, and just *using* the tool.

**Comment by rsheeter** [comment]
I think if I add backtraces in a debug log both users are happy?
