### ISSUE TITLE
Panic in `fixed_impl` triggered by `VariationAxisRecord::normalize`

### ISSUE THREAD

**Issue by drott** [googlefonts/fontations#958]
https://oss-fuzz.com/testcase-detail/5278123998904320 found a panic in `VariationAxisRecord::normalize` - but this issue got marked as fixed because presumably a subsequent fuzzer logic change used the entropy differently and did not reach this code anymore.

It is however still reproducible with:
```
$ git revert 4e5fde8a3da573467a29ca3d46ca00fddc317e1c
$ target/debug/fuzz_skrifa_outline clusterfuzz-testcase-minimized-fuzz_skrifa_outline-5278123998904320
```

```
thread '<unnamed>' panicked at /Users/drott/dev/fontations/font-types/src/fixed.rs:279:1:
attempt to subtract with overflow
```

Not sure if and how we want to fix this? Would it make sense to use saturating arithmetic here?

**Comment by dfrg** [comment]
I’d lean towards making these explicitly wrapping as that would match FT. The secondary question is what to do about `AxisRecord::normalize()` when `!(min <= default <= max)`. Should we just return 0 when the values are not appropriately ordered?

**Comment by drott** [comment]
Yes, I think we could set it to 0, clamped by min and max. 

Thinking further: In the normalization we have no means to return an `Err()` anywhere, but could we perhaps sanitize earlier in loading and reject the font instantiation? On the other hand, the OpenType spec does not _explicitly_ require this order, only explains the normalization maths which implicitly assumes the order. So I lean towards not rejecting such a font.
https://learn.microsoft.com/en-us/typography/opentype/spec/fvar#variationaxisrecord 
https://learn.microsoft.com/en-us/typography/opentype/spec/otvaroverview#CSN

**Comment by dfrg** [comment]
Agreed on not rejecting the font. GIGO seems to be our mantra.

**Comment by drott** [comment]
In https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69787 and https://oss-fuzz.com/testcase-detail/6159008335986688 the fuzzer found this again on ToT.
